services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
